# Generated by Django 5.2.1 on 2025-05-12 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='e_mail',
            new_name='email_address',
        ),
    ]
